version: "3"
services:
    nginx:
        ports:
            - "80:80"
    node-app:
        build:
            context: .
            args:
                NODE_ENV: production
        environment: 
            - NODE_ENV=production
            - MONGO_USER=trial
            - MONGO_PASSWORD=error
            - SESSION_SECRET=session
        command: node index.js
    mongo:
        environment:
            - MONGO_INITDB_ROOT_USERNAME=trial
            - MONGO_INITDB_ROOT_PASSWORD=error
